version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: netflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
  
  netflix-api:
    build:
      context: ../NetflixApi(.net)
      dockerfile: ../docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - CONNECTION_STRING=Host=postgres;Database=netflix;Username=admin;Password=secret

  graphql-api:
    build:
      context: ../graphql-api
      dockerfile: ../docker/Dockerfile.graphql
    depends_on:
      - netflix-api
    ports:
      - "4000:4000"

  react-client:
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile.react
    ports:
      - "3000:3000"
    depends_on:
      - graphql-api
